apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: feed-reader-dotnet
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: feed-reader-dotnet
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "3"
  source:
    git:
      url: https://github.com/jrobinsonvm/simple-feed-reader
      ref:
        branch: main
